### ISSUE TITLE
wrong result in r2c 1d strided FFT with hipfftPlanMany

### ISSUE THREAD

**Issue by bd4** [ROCmSoftwarePlatform/hipFFT#8]
### What is the expected behavior
-  FFT r2c of batched `[2 3 -1 4]` and `[7, -21, 11, 1]` is `[( 8.000,  0.000) ( 3.000,  1.000) (-6.000,  0.000)]` and `[ (-2.000,  0.000)(-4.000, 22.000) (38.000,  0.000)]`

### What actually happens
-  If strides are 1, it works. If not, result is not correct. Note that using cufft, the correct result is produced with non unit strides.

### How to reproduce
-  See https://github.com/bd4/hip-bugs/blob/main/fft_strided.cxx

### Environment
| Hardware | description |
|-----|-----|
| GPU | gfx803 Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] |
| CPU | Intel i7-8700K  |

| Software | version |
|-----|-----|
| ROCm | v4.3 |

**Comment by evetsso** [comment]
It looks like `hipfftPlanMany` is incorrectly failing, which is causing later test steps to produce incorrect results.

The supplied strides only make sense for an out-of-place transform.  `hipfftPlanMany` builds both in-place and out-of-place transforms because it is not told at plan creation time which one will actually be executed.  hipFFT is incorrectly treating this situation as an error because the in-place plan creation fails.

**Comment by bd4** [comment]
Thanks for looking at this! Seems like an unfortunate choice in the cuFFT plan many API.

I added rval checks to my reproducer - the hipfftPlanMany still returns HIPFFT_SUCCESS, is it an internal call that is failing and not propagating? The reproducer is based on the following gtensor test: https://github.com/wdmapp/gtensor/blob/main/tests/test_fft.cxx#L108

**Comment by evetsso** [comment]
https://github.com/ROCmSoftwarePlatform/hipFFT/commit/feb9cb9bf0371d462149ef61d0db7dad68cbcfc6 in master should fix this.

**Comment by bd4** [comment]
I cherry picked this into `release/rocm-rel-4.3`, to avoid having to build an entire ROCm stack, and it doesn't fix the issue for me. The test case still has unit strides - are you sure this fixed non equal non unit stride case? While the cherry pick applied cleanly, I guess it's possible it relies on some other fix. Any advice on building the latest master/develop branches without rebuilding all of ROCm?

**Comment by evetsso** [comment]
Ok, when I recheck with your updated reproducer, I see the remaining problem.  I'll investigate.

**Comment by evetsso** [comment]
Oh, did you forget to zero out d_A2?  It looks like the differences are due to uninitialized memory.  Adding:
```c++
CHECK(hipMemset(d_A2, 0, rbytes));
```
fixes things for me.

**Comment by bd4** [comment]
Agreed that should be zeroed too, but I guess on my machine I was lucky and it was already zeros, I get same result with or without it:
```
$ LD_LIBRARY_PATH=$HOME/soft/hipfft/hip-43/lib ./fft_strided_hip 
         A: [ 2.000,  0.000,  3.000,  0.000, -1.000,  0.000,  4.000,  0.000,  7.000,  0.000, -21.000,  0.000, 11.000,  0.000,  1.000,  0.000]
Arrays not close (max 1e-06) at fft_strided.cxx:157
 err 3 at [0]
h_B_expected: [( 8.000,  0.000) ( 0.000,  0.000) ( 0.000,  0.000) ( 3.000,  1.000) ( 0.000,  0.000) ( 0.000,  0.000) (-6.000,  0.000) ( 0.000,  0.000) ( 0.000,  0.000) (-2.000,  0.000) ( 0.000,  0.000) ( 0.000,  0.000) (-4.000, 22.000) ( 0.000,  0.000) ( 0.000,  0.000) (38.000,  0.000) ( 0.000,  0.000) ( 0.000,  0.000)]
h_B         : [( 5.000,  0.000) (-1.000,  0.000) ( 5.000,  0.000) ( 0.000,  0.000) ( 0.000,  0.000) ( 0.000,  0.000) ( 0.000,  0.000) ( 0.000,  0.000) ( 0.000,  0.000) (-14.000,  0.000) (28.000,  0.000) (-14.000,  0.000) ( 0.000,  0.000) ( 0.000,  0.000) ( 0.000,  0.000) ( 0.000,  0.000) ( 0.000,  0.000) ( 0.000,  0.000)]
Arrays not close (max 1e-06) at fft_strided.cxx:162
 err 1 at [4]
       h_A: [ 2.000,  0.000,  3.000,  0.000, -1.000,  0.000,  4.000,  0.000,  7.000,  0.000, -21.000,  0.000, 11.000,  0.000,  1.000,  0.000]
      h_A2: [ 2.000,  0.000,  3.000,  0.000,  0.000,  0.000,  0.000,  0.000,  7.000,  0.000, -21.000,  0.000,  0.000,  0.000,  0.000,  0.000]
``` 

Note that B is wrong and d_B is zeroed (so A2 may actually be correct for that B). I verified I am using my custom build hipfft.so with ldd. If it's working for you though, maybe it is an issue with how I cherry picked the fix to the 4.3 release branch. The master branch didn't want to build against my ROCm 4.3 install, and I haven't seen a reasonably easy way to build latest full ROCm stack from source. Maybe there is some way I can hack master hipFFT build to accept 4.3, or were there deeper changes that make this difficult?

**Comment by bd4** [comment]
I think your latest commit may have fixed my issue - I build develop branch against my ROCm 4.3 install (including the 4.3 version of rocFFT), and I am still getting the same result. So maybe there is a rocFFT change involved in the fix as well?

**Comment by bd4** [comment]
Confirmed fixed using latest hipFFT + rocFFT and zeroing A2. Took me a while to build rocFFT, and my VM ran out of disk space... Closing now.
